### ISSUE TITLE
catched a crash.

### ISSUE THREAD

**Issue by IrvingRyan** [google/hover#25]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: io.mattcarroll.hover.hoverdemo, PID: 15843
                                                                                java.lang.IllegalArgumentException: View=io.mattcarroll.hover.defaulthovermenu.HoverMenuView{42e09eb0 V.E..... ......ID 0,0-1080,1845} not attached to window manager
                                                                                    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:389)
                                                                                    at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:304)
                                                                                    at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:74)
                                                                                    at io.mattcarroll.hover.defaulthovermenu.window.WindowViewController.makeTouchable(WindowViewController.java:93)
                                                                                    at io.mattcarroll.hover.defaulthovermenu.window.WindowHoverMenu$1.onExpanded(WindowHoverMenu.java:69)
                                                                                    at io.mattcarroll.hover.defaulthovermenu.HoverMenuView$11.run(HoverMenuView.java:445)
                                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:157)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5335)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by matthew-carroll** [comment]
Hi @IrvingRyan, which version of Hover is this from?

**Comment by IrvingRyan** [comment]
how's that crash happened.
1.launch Demo
2.click "LAUNCH MENU"
3.hide the hover view
4.then click "LAUNCH HOVER MENU ACTIVITY"
5.try to hide this hover view ,but it still display,then quick double click it , crash...

**Comment by IrvingRyan** [comment]
I ran this source code directly.

**Comment by matthew-carroll** [comment]
Thanks.  I'll attempt to repro the issue when I get a few minutes.

**Comment by wutongke** [comment]
I saw the same crash

**Comment by Aexyn** [comment]
same crash


```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: io.mattcarroll.hover.hoverdemo, PID: 23125
                  java.lang.IllegalArgumentException: View=io.mattcarroll.hover.defaulthovermenu.HoverMenuView{4fe24a7 V.E...... ......ID 0,0-1080,1704} not attached to window manager
                      at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
                      at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:336)
                      at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:91)
                      at io.mattcarroll.hover.defaulthovermenu.window.WindowViewController.makeUntouchable(WindowViewController.java:99)
                      at io.mattcarroll.hover.defaulthovermenu.window.WindowHoverMenu$1.onCollapsed(WindowHoverMenu.java:59)
                      at io.mattcarroll.hover.defaulthovermenu.HoverMenuView$4$1.onPullToSideCompleted(HoverMenuView.java:170)
                      at io.mattcarroll.hover.defaulthovermenu.MagnetPositioner$2.onAnimationEnd(MagnetPositioner.java:56)
                      at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                      at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                      at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                      at android.view.Choreographer.doFrame(Choreographer.java:603)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                      at android.os.Handler.handleCallback(Handler.java:746)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```
