### ISSUE TITLE
non-fullscreen demo crash

### ISSUE THREAD

**Issue by ljoaquin** [google/hover#46]
launch menu and drag to X to close it
repeat this a few times
then crash

> 03-30 19:40:49.267 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/WindowDragWatcher: ACTION_MOVE. motionX: 721.19806, motionY: 1896.4106
03-30 19:40:49.267 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: Setting collapsed position - x: 583, y: 1686
03-30 19:40:49.284 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/WindowDragWatcher: ACTION_MOVE. motionX: 718.56714, motionY: 1914.4631
03-30 19:40:49.285 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: Setting collapsed position - x: 580, y: 1704
03-30 19:40:49.291 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: Menu released at - x: 580.56714, y: 1704.4631
03-30 19:40:49.291 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: stopDragMode()
03-30 19:40:49.292 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: Hover menu dropped in exit region. Requesting exit.
03-30 19:40:49.292 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuService: Menu exit requested.
03-30 19:40:49.365 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuService: onDestroy()
03-30 19:40:49.999 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuService: onCreate()
03-30 19:40:50.000 375-1058/? D/audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
03-30 19:40:50.001 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/CollapsedMenuAnchor: setAnchorAt() - side: 2, normalized Y: 0.49870017
03-30 19:40:50.001 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: init()
03-30 19:40:50.005 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: setAdapter()
03-30 19:40:50.006 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: Setting tab ID to: 48
03-30 19:40:50.006 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: Adding first tab: 0
03-30 19:40:50.010 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuService: onStartCommand() - showing Hover menu.
03-30 19:40:50.018 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: animateActiveTabToAnchorPosition()
03-30 19:40:50.018 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuView: Active tab location - left: 0.0, top: 0.0
03-30 19:40:50.018 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/HoverMenuWindowSidePuller: Pulling to side. Anchor - side: 2, normalized Y: 0.49870017
03-30 19:40:50.018 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/CollapsedMenuAnchor: Creating a new anchor position on the RIGHT side at a normalized vertical position: 0.49870017
03-30 19:40:50.019 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/CollapsedMenuAnchor: Anchoring bounds with height: 0
03-30 19:40:50.019 21848-21848/io.mattcarroll.hoverdemonon_fullscreen D/AndroidRuntime: Shutting down VM
beginning of crash
03-30 19:40:50.020 21848-21848/io.mattcarroll.hoverdemonon_fullscreen E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: io.mattcarroll.hoverdemonon_fullscreen, PID: 21848
                                                                                        java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Rect.right' on a null object reference
                                                                                            at io.mattcarroll.hover.defaulthovermenu.CollapsedMenuAnchor.anchor(CollapsedMenuAnchor.java:165)
                                                                                            at io.mattcarroll.hover.defaulthovermenu.MagnetPositioner.pullToAnchor(MagnetPositioner.java:76)
                                                                                            at io.mattcarroll.hover.defaulthovermenu.HoverMenuView.animateActiveTabToAnchorPosition(HoverMenuView.java:944)
                                                                                            at io.mattcarroll.hover.defaulthovermenu.HoverMenuView.access$2200(HoverMenuView.java:65)
                                                                                            at io.mattcarroll.hover.defaulthovermenu.HoverMenuView$10.run(HoverMenuView.java:400)
                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-30 19:40:50.021 937-1841/? W/ActivityManager:   Force finishing activity io.mattcarroll.hoverdemonon_fullscreen/.MainActivity

**Comment by matthew-carroll** [comment]
Version 0.9.8 just shipped.  Please re-open this issue with an updated stacktrace if it continues to happen on 0.9.8.
