### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by pourya0111** [google/hover#76]
whats problem?

java.lang.RuntimeException: Cannot obtain HoverThemeManager before calling init().

`FATAL EXCEPTION: main
                                                                            Process: com.izigaaps.myapplication, PID: 29811
                                                                            java.lang.RuntimeException: Unable to start service com.izigaaps.myapplication.DemoHoverMenuService@41d70530 with Intent { cmp=com.izigaaps.myapplication/.DemoHoverMenuService }: java.lang.RuntimeException: Cannot obtain HoverThemeManager before calling init().
                                                                                at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2883)
                                                                                at android.app.ActivityThread.access$2100(ActivityThread.java:151)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5421)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: java.lang.RuntimeException: Cannot obtain HoverThemeManager before calling init().
                                                                                at com.izigaaps.myapplication.theming.HoverThemeManager.getInstance(HoverThemeManager.java:19)
                                                                                at com.izigaaps.myapplication.DemoHoverMenuFactory.createDemoMenuFromCode(DemoHoverMenuFactory.java:49)
                                                                                at com.izigaaps.myapplication.DemoHoverMenuService.createHoverMenu(DemoHoverMenuService.java:51)
                                                                                at com.izigaaps.myapplication.DemoHoverMenuService.onHoverMenuLaunched(DemoHoverMenuService.java:45)
                                                                                at io.mattcarroll.hover.window.HoverMenuService.initHoverMenu(HoverMenuService.java:118)
                                                                                at io.mattcarroll.hover.window.HoverMenuService.onStartCommand(HoverMenuService.java:88)
                                                                                at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2866)
                                                                                at android.app.ActivityThread.access$2100(ActivityThread.java:151) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
`

**Comment by pourya0111** [comment]
bump @matthew-carroll
